version: "3.5"
services:
  app:
    container_name: all-foods-container
    image: node:16-alpine
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c "yarn install && yarn dev"
    ports:
      - "5173:5173"
